# Generated by Django 5.1.3 on 2024-11-26 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editable_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='viewable_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
