# Generated by Django 5.1.3 on 2024-11-26 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_file_editors_file_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
